export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const ADD_LOADING = 'ADD_LOADING';
export const ADD_LOADING_SUCCESS = 'ADD_LOADING_SUCCESS';
export const REMOVE_LOADING = 'REMOVE_LOADING';
export const REMOVE_LOADING_SUCCESS = 'REMOVE_LOADING_SUCCESS';

export const GET_COPARENTS = 'GET_COPARENTS';
export const GET_COPARENTS_SUCCESS = 'GET_COPARENTS_SUCCESS';

export const GET_CHILDREN = 'GET_CHILDREN';
export const GET_CHILDREN_SUCCESS = 'GET_CHILDREN_SUCCESS';
